import { initializeApp } from "https://www.gstatic.com/firebasejs/10.8.0/firebase-app.js";
import { getAuth, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.8.0/firebase-auth.js";
import { getFirestore, doc, updateDoc, increment } from "https://www.gstatic.com/firebasejs/10.8.0/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyC5c-np0wNIMkcowH4Rr1i5r3B2-qGY1e4",authDomain:"ishan-fun.firebaseapp.com",projectId:"ishan-fun",storageBucket:"ishan-fun.firebasestorage.app",messagingSenderId:"919307010777",appId:"1:919307010777:web:35b659050c32e7c05c74c8",measurementId:"G-S8H37T0FNX"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
let currentUser=null; onAuthStateChanged(auth,u=>currentUser=u);

const screens={difficulty:document.getElementById("difficulty-screen"),gameplay:document.getElementById("gameplay-screen"),gameover:document.getElementById("gameover-screen")};
const canvas=document.getElementById("snake-board"),ctx=canvas.getContext("2d");
const appleEl=document.getElementById("apple-count"),lengthEl=document.getElementById("length-count"),modeEl=document.getElementById("current-mode-tag");
const configs={normal:{cols:24,rows:18,cell:28,target:20,interval:135},hardcore:{cols:28,rows:20,cell:25,target:50,interval:82}};
const state={mode:"normal",snake:[],apple:null,direction:{x:1,y:0},nextDirection:{x:1,y:0},apples:0,running:false,gameOver:false,timer:null,lastStep:0};

let audio=null;
function audioCtx(){if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();return audio}
function tone(freq,dur,type="sine",vol=.08){const c=audioCtx(),o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.setValueAtTime(freq,c.currentTime);g.gain.setValueAtTime(vol,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+dur);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+dur)}
function eatSfx(){tone(680,.08,"sine",.09);setTimeout(()=>tone(920,.1,"triangle",.07),45)}
function crashSfx(){tone(180,.28,"sawtooth",.08)}
function winSfx(){[523.25,659.25,783.99,1046.5].forEach((f,i)=>setTimeout(()=>tone(f,.18,"triangle",.11),i*75))}

function screen(name){Object.entries(screens).forEach(([k,e])=>{e.classList.toggle("active",k===name);e.setAttribute("aria-hidden",String(k!==name))})}
function resizeCanvas(){const c=configs[state.mode];canvas.width=c.cols*c.cell;canvas.height=c.rows*c.cell;draw()}
function randomCell(){const c=configs[state.mode];return{x:Math.floor(Math.random()*c.cols),y:Math.floor(Math.random()*c.rows)}}
function same(a,b){return a.x===b.x&&a.y===b.y}
function spawnApple(){const c=configs[state.mode];let p;do{p=randomCell()}while(state.snake.some(seg=>same(seg,p)));state.apple=p}
function updateUI(){const target=configs[state.mode].target;appleEl.textContent=`${state.apples} / ${target}`;lengthEl.textContent=String(state.snake.length)}
function draw(){if(!canvas.width)return;const c=configs[state.mode];ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle="#0d0d10";ctx.fillRect(0,0,canvas.width,canvas.height);
  ctx.strokeStyle="rgba(255,255,255,.045)";ctx.lineWidth=1;for(let x=0;x<=c.cols;x++){ctx.beginPath();ctx.moveTo(x*c.cell+.5,0);ctx.lineTo(x*c.cell+.5,canvas.height);ctx.stroke()}for(let y=0;y<=c.rows;y++){ctx.beginPath();ctx.moveTo(0,y*c.cell+.5);ctx.lineTo(canvas.width,y*c.cell+.5);ctx.stroke()}
  if(state.apple){const cx=state.apple.x*c.cell+c.cell/2,cy=state.apple.y*c.cell+c.cell/2,r=c.cell*.27;ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.fillStyle="#f87171";ctx.shadowBlur=18;ctx.shadowColor="rgba(248,113,113,.65)";ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#4ade80";ctx.fillRect(cx+r*.35,cy-r*1.1,3,7)}
  state.snake.forEach((seg,i)=>{const pad=i===0?3:4;const x=seg.x*c.cell+pad,y=seg.y*c.cell+pad,w=c.cell-pad*2;ctx.fillStyle=i===0?"#ffffff":"#b4b4bb";ctx.shadowBlur=i===0?14:0;ctx.shadowColor="rgba(255,255,255,.32)";roundRect(ctx,x,y,w,w,Math.min(7,w*.22));ctx.fill();ctx.shadowBlur=0});
}
function roundRect(c,x,y,w,h,r){c.beginPath();c.moveTo(x+r,y);c.arcTo(x+w,y,x+w,y+h,r);c.arcTo(x+w,y+h,x,y+h,r);c.arcTo(x,y+h,x,y,r);c.arcTo(x,y,x+w,y,r);c.closePath()}
function setDirection(x,y){if(!state.running)return;if(x===-state.direction.x&&y===-state.direction.y)return;if(x===-state.nextDirection.x&&y===-state.nextDirection.y)return;state.nextDirection={x,y}}
function keyHandler(e){const key=e.key.toLowerCase();const map={arrowup:[0,-1],w:[0,-1],arrowdown:[0,1],s:[0,1],arrowleft:[-1,0],a:[-1,0],arrowright:[1,0],d:[1,0]};if(map[key]){e.preventDefault();setDirection(...map[key])}}
function start(mode){const c=configs[mode];state.mode=mode;state.snake=[{x:Math.floor(c.cols/2),y:Math.floor(c.rows/2)}];state.direction={x:1,y:0};state.nextDirection={x:1,y:0};state.apples=0;state.running=true;state.gameOver=false;state.lastStep=performance.now();modeEl.textContent=mode.toUpperCase();modeEl.classList.toggle("hardcore",mode==="hardcore");spawnApple();updateUI();resizeCanvas();screen("gameplay");clearTimeout(state.timer);state.timer=requestAnimationFrame(loop)}
function loop(now){if(!state.running)return;if(now-state.lastStep>=configs[state.mode].interval){state.lastStep=now;step()}state.timer=requestAnimationFrame(loop)}
function step(){state.direction={...state.nextDirection};const head={x:state.snake[0].x+state.direction.x,y:state.snake[0].y+state.direction.y};const c=configs[state.mode];const wall=head.x<0||head.x>=c.cols||head.y<0||head.y>=c.rows;const eating=state.apple&&same(head,state.apple);const bodyToCheck=eating?state.snake:state.snake.slice(0,-1);const self=bodyToCheck.some(seg=>same(seg,head));if(wall||self){end(false);return}state.snake.unshift(head);if(eating){state.apples++;eatSfx();if(state.apples>=c.target){end(true);return}spawnApple()}else state.snake.pop();updateUI();draw()}
async function award(pts,hcp){if(!currentUser)return;try{await updateDoc(doc(db,"users",currentUser.uid),{points:increment(pts),hcPoints:increment(hcp)})}catch(e){console.error("Failed to sync Snake reward:",e)}}
function toast(title,desc,hard=false){let box=document.getElementById("achievement-toast-container");if(!box)return;const t=document.createElement("div");t.className=`achievement-toast ${hard?"hard-tier":""}`;t.innerHTML=`<div class="toast-info"><span class="toast-title">${title}</span><span class="toast-desc">${desc}</span></div><span class="toast-badge locked">LOCKED</span>`;box.appendChild(t);setTimeout(()=>{const b=t.querySelector(".toast-badge");if(b){b.textContent="COMPLETED";b.className=`toast-badge completed-pop ${hard?"hard-tier-badge":""}`}},600);setTimeout(()=>t.classList.add("toast-hide"),3800);setTimeout(()=>t.remove(),4200);tone(523,.12,"triangle",.09);setTimeout(()=>tone(659,.12,"triangle",.09),70);setTimeout(()=>tone(784,.16,"triangle",.09),140)}
function announce(id,title,description,hard=false){const event={id,title,description,isHardTier:hard,nonce:`${Date.now()}-${Math.random()}`};toast(title,description,hard);try{const bus=new BroadcastChannel("ishan-fun-achievements");bus.postMessage(event);bus.close()}catch{}try{localStorage.setItem("ishan_fun_achievement_event",JSON.stringify(event))}catch{}}
function checkHardcoreSlayer(){const completed=["ach_hardcore_button","ach_hardcore_elemental","ach_hardcore_snake"].filter(k=>localStorage.getItem(k)==="true").length;if(completed>=2&&localStorage.getItem("ach_hardcore_slayer")!=="true"){localStorage.setItem("ach_hardcore_slayer","true");announce("hardcore-slayer","Hardcore Slayer","Beat 2 games on Hardcore Mode.",true);award(0,5)}}
function finishAchievement(){if(state.mode==="hardcore"){if(localStorage.getItem("ach_hardcore_survivor")!=="true"){localStorage.setItem("ach_hardcore_survivor","true");announce("hardcore-survivor","Hardcore Survivor","Beat any game in Hardcore Mode.",true)}if(localStorage.getItem("ach_hardcore_snake")!=="true"){localStorage.setItem("ach_hardcore_snake","true");checkHardcoreSlayer()}}}
function end(won){if(state.gameOver)return;state.gameOver=true;state.running=false;cancelAnimationFrame(state.timer);won?winSfx():crashSfx();const c=configs[state.mode];document.getElementById("result-eyebrow").textContent=won?"RUN COMPLETE":"RUN ENDED";document.getElementById("result-title").textContent=won?"YOU WIN":"GAME OVER";document.getElementById("result-sub").textContent=won?`You ate ${c.target} apples and grew to ${state.snake.length}.`:`The snake crashed after ${state.apples} apple${state.apples===1?"":"s"}.`;document.getElementById("reward-label").textContent=won?"REWARD":"APPLES EATEN";document.getElementById("final-apples").textContent=won?(state.mode==="hardcore"?"+5 HCP":"+5 PTS"):String(state.apples);document.getElementById("final-mode").textContent=state.mode.toUpperCase()+" MODE";document.getElementById("final-length").textContent=String(state.snake.length);document.getElementById("final-target").textContent=String(c.target);if(won){award(state.mode==="normal"?5:0,state.mode==="hardcore"?5:0);finishAchievement()}screen("gameover")}

document.getElementById("select-normal-btn").addEventListener("click",()=>start("normal"));document.getElementById("select-hardcore-btn").addEventListener("click",()=>start("hardcore"));document.getElementById("play-again-btn").addEventListener("click",()=>start(state.mode));window.addEventListener("keydown",keyHandler);window.addEventListener("resize",resizeCanvas);
