import {initializeApp} from "https://www.gstatic.com/firebasejs/10.8.0/firebase-app.js";
import {getAuth,onAuthStateChanged} from "https://www.gstatic.com/firebasejs/10.8.0/firebase-auth.js";
import {getFirestore,doc,updateDoc,increment} from "https://www.gstatic.com/firebasejs/10.8.0/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyC5c-np0wNIMkcowH4Rr1i5r3B2-qGY1e4",authDomain:"ishan-fun.firebaseapp.com",projectId:"ishan-fun",storageBucket:"ishan-fun.firebasestorage.app",messagingSenderId:"919307010777",appId:"1:919307010777:web:35b659050c32e7c05c74c8",measurementId:"G-S8H37T0FNX"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);let currentUser=null;onAuthStateChanged(auth,u=>currentUser=u);
const TARGET=100,MAX=5,NORMAL=[1,2,5,10,15,20],HARD=[1,.75,.5,.25,.125,.1];let hardcore=false,clicks=0,rawClicks=0,rebirths=0,ready=false,finished=false;
let audio=null;function ctx(){if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();return audio}
function clickSfx(){const c=ctx(),o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.setValueAtTime(600,c.currentTime);o.frequency.exponentialRampToValueAtTime(150,c.currentTime+.05);g.gain.setValueAtTime(.15,c.currentTime);g.gain.exponentialRampToValueAtTime(.01,c.currentTime+.05);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.05)}
function rebirthSfx(){const c=ctx();[300,450,600,800].forEach((f,i)=>{const o=c.createOscillator(),g=c.createGain(),t=c.currentTime+i*.06;o.type='triangle';o.frequency.setValueAtTime(f,t);g.gain.setValueAtTime(.15,t);g.gain.exponentialRampToValueAtTime(.001,t+.2);o.connect(g);g.connect(c.destination);o.start(t);o.stop(t+.2)})}
function achievementSfx(){const c=ctx();[523.25,659.25,783.99,1046.5].forEach((f,i)=>{const o=c.createOscillator(),g=c.createGain(),t=c.currentTime+i*.07;o.type='triangle';o.frequency.setValueAtTime(f,t);g.gain.setValueAtTime(.2,t);g.gain.exponentialRampToValueAtTime(.001,t+.25);o.connect(g);g.connect(c.destination);o.start(t);o.stop(t+.25)})}
function toast(title,desc,hard=false){let box=document.getElementById('achievement-toast-container'),t=document.createElement('div');t.className='achievement-toast '+(hard?'hard-tier':'');t.innerHTML=`<div class="toast-info"><span class="toast-title">${title}</span><span class="toast-desc">${desc}</span></div><span class="toast-badge locked">LOCKED</span>`;box.appendChild(t);achievementSfx();setTimeout(()=>{const b=t.querySelector('.toast-badge');b.textContent='COMPLETED';b.className='toast-badge completed-pop '+(hard?'hard-tier-badge':'')},600);setTimeout(()=>t.classList.add('toast-hide'),3800);setTimeout(()=>t.remove(),4200)}
const bus='BroadcastChannel'in window?new BroadcastChannel('ishan-fun-achievements'):null;function announce(id,title,desc,hard=false){const e={id,title,description:desc,isHardTier:hard,nonce:Date.now()+'-'+Math.random()};toast(title,desc,hard);bus?.postMessage(e);try{localStorage.setItem('ishan_fun_achievement_event',JSON.stringify(e))}catch(_){} }
const screens={difficulty:document.getElementById('difficulty-screen'),gameplay:document.getElementById('gameplay-screen'),gameover:document.getElementById('gameover-screen')};function screen(n){Object.entries(screens).forEach(([k,e])=>{e.classList.toggle('active',k===n);e.setAttribute('aria-hidden',String(k!==n))})}
const clickEl=document.getElementById('click-count'),rebirthEl=document.getElementById('rebirth-count'),btn=document.getElementById('main-click-btn'),particles=document.getElementById('particle-layer'),modeTag=document.getElementById('current-mode-tag'),progress=document.getElementById('progress-container'),fill=document.getElementById('progress-fill'),ptext=document.getElementById('progress-text'),rebirthBtn=document.getElementById('rebirth-btn'),finishBtn=document.getElementById('finish-btn');
function fmt(n){return Number.isInteger(n)?n.toLocaleString():n.toLocaleString(undefined,{maximumFractionDigits:3})}function value(){return(hardcore?HARD:NORMAL)[Math.min(rebirths,5)]}
function actions(which){[progress,rebirthBtn,finishBtn].forEach(e=>e.classList.remove('visible'));which.classList.add('visible')}
function ui(){clickEl.textContent=fmt(clicks);rebirthEl.textContent=`${rebirths} / ${MAX}`;fill.style.width=Math.min(100,clicks)+'%';ptext.textContent=`${fmt(clicks)} / ${TARGET}`;if(clicks>=TARGET&&!ready){ready=true;actions(rebirths<MAX?rebirthBtn:finishBtn)}}
function particle(v){const p=document.createElement('span');p.className='click-particle '+(hardcore?'hardcore':'');p.textContent='+'+fmt(v);p.style.setProperty('--x',Math.round((Math.random()-.5)*120)+'px');particles.appendChild(p);setTimeout(()=>p.remove(),720)}
function animateButton(){btn.classList.remove('soft-pop');void btn.offsetWidth;btn.classList.add('soft-pop','is-active');setTimeout(()=>btn.classList.remove('is-active'),105)}
function start(h){hardcore=h;clicks=0;rawClicks=0;rebirths=0;ready=false;finished=false;modeTag.textContent=h?'HARDCORE':'NORMAL';modeTag.classList.toggle('hardcore',h);screen('gameplay');actions(progress);fill.style.width='0%';ui()}
async function award(pts,hcp){if(!currentUser)return;try{await updateDoc(doc(db,'users',currentUser.uid),{points:increment(pts),hcPoints:increment(hcp)})}catch(e){console.error('Failed to sync reward:',e)}}
function mainClick(e){e.preventDefault();if(finished)return;const v=value();clicks+=v;rawClicks++;clickSfx();animateButton();particle(v);ui();if(clicks>=1000&&rebirths===0&&localStorage.getItem('ach_button_smasher')!=='true'){localStorage.setItem('ach_button_smasher','true');announce('button-smasher','Button Smasher!','Reach 1,000 clicks in a single run without rebirthing.');award(10,0)}}
btn.addEventListener('pointerdown',mainClick);
rebirthBtn.addEventListener('click',()=>{rebirthSfx();rebirths++;clicks=0;ready=false;rebirthBtn.classList.remove('visible');setTimeout(()=>{actions(progress);fill.style.width='0%';ui()},280)});
finishBtn.addEventListener('click',()=>{if(finished||rebirths<MAX||clicks<TARGET)return;finished=true;achievementSfx();document.getElementById('final-clicks').textContent=fmt(clicks);document.getElementById('final-mode').textContent=hardcore?'HARDCORE MODE':'NORMAL MODE';document.getElementById('final-points').textContent=hardcore?'+5 HCP':'+5 PTS';document.getElementById('reward-label').textContent=hardcore?'HCP EARNED':'PTS EARNED';if(hardcore){if(localStorage.getItem('ach_hardcore_survivor')!=='true'){localStorage.setItem('ach_hardcore_survivor','true');announce('hardcore-survivor','Hardcore Survivor','Beat any game in Hardcore Mode.',true)}award(0,5)}else award(5,0);screen('gameover')});
document.getElementById('select-normal-btn').addEventListener('click',()=>start(false));document.getElementById('select-hardcore-btn').addEventListener('click',()=>start(true));document.getElementById('play-again-btn').addEventListener('click',()=>screen('difficulty'));
document.addEventListener('keydown',e=>{if(screens.gameplay.classList.contains('active')&&(e.code==='Space'||e.code==='Enter')){if(e.code==='Enter'&&document.activeElement!==btn)return;e.preventDefault();mainClick(e)}});
